---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
spec:
  template:
    metadata:
      name:  init-db
      labels:
        app: init-postgresdb
    spec:
      containers:
      - image: "postgres:12.10"
        name: init-db
        command: [ "bin/sh", "-c", "psql -a -f /brizer.sql" ]
        volumeMounts:
        - name: db-init
          mountPath: /brizer.sql
        env:
          - name: PGHOST
            valueFrom:
              configMapKeyRef:
                name: postgres-secret
                key: PGHOST
          - name: PGDATABASE
            valueFrom:
              configMapKeyRef:
                name: postgres-secret
                key: PGDATABASE
          - name: PGUSER
            valueFrom:
              configMapKeyRef:
                name: postgres-secret
                key: PGUSER
          - name: PGPASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-secret
                key: PGPASSWORD
      volumes:
        - name: db-init
          configMap:
            name: brizer.sql
      restartPolicy: OnFailure