apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  # PGDATABASE: brizer
  # PGUSER: brizer
  PGHOST: 'postgres.default.svc.cluster.local'
  # Default superuser
  POSTGRES_USER: brizer
  # Default superuser password
  POSTGRES_PASSWORD: changeme
  # Default database
  POSTGRES_DB: brizer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.10
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem      
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: postgres-volume
#   labels:
#     type: local
#     app: postgres
# spec:
#   storageClassName: local-path
#   capacity: 
#     storage: 2Gi
#   accessModes:
#     - ReadWriteOnce
#   volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432