---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
spec:
  template:
    metadata:
      name:  init-db
      labels:
        app: init-postgresdb
    spec:
      containers:
      - image: "postgres:12.10"
        name: init-db
        command: [ "bin/sh", "-c", "sleep 1000; psql -a -f /tmp/hospital/brizer.sql" ]
        volumeMounts:
        - name: db-init
          mountPath: /tmp/hospital
        env:
          - name: PGHOST
            valueFrom:
              configMapKeyRef:
                name: postgres-secret
                key: PGHOST
          - name: PGDATABASE
            valueFrom:
              configMapKeyRef:
                name: postgres-secret
                key: POSTGRES_DB
          - name: PGUSER
            valueFrom:
              configMapKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
          - name: PGPASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
      volumes:
        - name: db-init
          configMap:
            name: db-init
      restartPolicy: OnFailure