apiVersion: v1
kind: Service
metadata:
  name: hospital
  labels:
    app: hospital
spec:
  type: ClusterIP
  selector:
    app: hospital
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hospital
  name: hospital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital
  template:
    metadata:
      labels:
        app: hospital
    spec:
      containers:
      - image: core.fert.name/library/hospital:IMAGE_TAG
        name: hospital
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hospital
  labels:
    app.kubernetes.io/instance: hospital
    app.kubernetes.io/name: hospital
spec:
  ingressClassName: nginx
  rules:
    - host: hospital.fert.name
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: hospital
                port:
                  number: 80
